spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luk1nov/microservices-demo-config.git
          skip-ssl-validation: true
          clone-on-start: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8888
